### ISSUE TITLE
Will you consider TensorInfo to support nlp or voice?

### ISSUE THREAD

**Issue by Channingss** [iwatake2222/InferenceHelper#30]
Thanks for your open source, I would like to extend this project to support speech or NLP models. I found the  TensorInfo does not support  nlp or voice .

https://github.com/iwatake2222/InferenceHelper/blob/9fbdc14f8a0fcd042519705ade6bc9a578cfd6b5/inference_helper/inference_helper.h#L26

**Comment by iwatake2222** [comment]
Good point!
Currently this library is tuned for image data (2d data). I also want to make it more general and able to use other data like 1D, sequencal or even table data.
However, it will require lots of work and refactoring most of code... So, I don't have plan to do it at the moment...

**Comment by iwatake2222** [comment]
This issue was closed because it has been inactive.
